
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.print.DocFlavor;
import javax.swing.JCheckBox;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author ludanyi.tamas
 */
public class FELULET extends javax.swing.JFrame {

    /**
     * Creates new form FELULET
     */
    private final String output = ",EESZT token kod kerem orizze meg: ";
    private final String outputTan = ",EESZT kod kerem orizze meg: ";
    private  String[] strSubstrings;
    private int index = 0;
    private final int substringSize = 11;
    private String input ;
    RANDOMPASS rp = new RANDOMPASS();
    public FELULET() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        NagyCHEK = new javax.swing.JCheckBox();
        kisCHEK = new javax.swing.JCheckBox();
        specCHEK = new javax.swing.JCheckBox();
        szamokCHEK = new javax.swing.JCheckBox();
        DBSZAM = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        telszamTEXT = new javax.swing.JTextField();
        passText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tördelő 1.0");

        jButton1.setText("GO!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jList1);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("Ide add meg a telfonszámokat!");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(jList2);

        NagyCHEK.setText("A-Z");
        NagyCHEK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NagyCHEKActionPerformed(evt);
            }
        });

        kisCHEK.setText("a-z");
        kisCHEK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kisCHEKActionPerformed(evt);
            }
        });

        specCHEK.setText("Spec Char");
        specCHEK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                specCHEKActionPerformed(evt);
            }
        });

        szamokCHEK.setText("1-9");
        szamokCHEK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                szamokCHEKActionPerformed(evt);
            }
        });

        jLabel2.setText("Hossz");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE)
                    .addComponent(jTextField1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(NagyCHEK, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(specCHEK, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGap(36, 36, 36))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(DBSZAM, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addComponent(jLabel2)))
                        .addGap(0, 34, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(szamokCHEK)
                            .addComponent(kisCHEK, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NagyCHEK, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(szamokCHEK))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kisCHEK)
                            .addComponent(specCHEK))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DBSZAM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );

        jTabbedPane1.addTab("TOKEN JELSZÓHOZ", jPanel1);

        jButton2.setText("GO!");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Telefonszám");

        jLabel4.setText("Jelszó");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane4.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(telszamTEXT, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(passText, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane4))
                        .addGap(43, 43, 43)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jLabel3)
                        .addGap(176, 176, 176)
                        .addComponent(jLabel4)))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telszamTEXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("TANÚSÍTVÁNY JELSZÓHOZ", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void szamokCHEKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_szamokCHEKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_szamokCHEKActionPerformed

    private void specCHEKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_specCHEKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_specCHEKActionPerformed

    private void kisCHEKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kisCHEKActionPerformed

    }//GEN-LAST:event_kisCHEKActionPerformed

    private void NagyCHEKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NagyCHEKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NagyCHEKActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        input  = jTextField1.getText();

        String array[] = null;

        String first4Char;
        String first2Char;
        first2Char = input.substring(0, 3);
        first4Char = input.substring(0, 4);

        if (input.length() > 15) {

            if (first2Char.equals("+36")) {
                array = input.split("\\+");
                jList2.setListData(passwordGen(array, index, rp, output));
                jList1.setListData(array);
            }   else if (first4Char.equals("0630") || first4Char.equals("0620") || first4Char.equals("0670")) {
                jList1.setListData(CharSplitBy11Count());
            }

        } else  if (input.length() < 15) {
            if(first2Char.equals("+36")){
                array = input.split("\\+");
                jList2.setListData(passwordGen(array, index, rp, output));
                jList1.setListData(array);
            }   else if (first4Char.equals("0630") || first4Char.equals("0620") || first4Char.equals("0670")) {

                jList1.setListData(CharSplitBy11Count());
            }
        }
        NullazCheckbox();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jTextArea1.setText(tanusitvanyJelszo());
        NullazCheckbox();
    }//GEN-LAST:event_jButton2ActionPerformed

    public String tanusitvanyJelszo(){
        String telszam = telszamTEXT.getText();
        String pass = passText.getText();
        int sorok = 1;
        telszam = telszam.replaceAll("[^0-9]", "");
        String firs4chAR=telszam.substring(0, 4);
        if(firs4chAR.equals("+363") || firs4chAR.equals("+362") || firs4chAR.equals("+367")){
            telszam = telszam.replace("+", "");
        }
        else if(firs4chAR.equals("0630") || firs4chAR.equals("0620") || firs4chAR.equals("0670")){
            
            telszam = telszam.replaceFirst("06", "36");
        }
        return sorok + ","+telszam+outputTan+pass;
        
    }
    
    
    public void NullazCheckbox() {
        jTextField1.setText("");
        passText.setText("");
        telszamTEXT.setText("");
        NagyCHEK.setSelected(false);
        kisCHEK.setSelected(false);
        specCHEK.setSelected(false);
        szamokCHEK.setSelected(false);
    }

    public String[] passwordGen(String[] array, int index, RANDOMPASS rp, String output) {
        input = jTextField1.getText();
        String array2[] = input.split("\\+");
        for (int i = 1; i < array.length; i++) {
            array[i] = array[i].replaceAll("[^0-9]", "");
            array[i] = array[i] += output;
            array2[i] = rp.RandomPASS(Integer.parseInt(DBSZAM.getText()), NagyCHEK.isSelected(), kisCHEK.isSelected(), specCHEK.isSelected(), szamokCHEK.isSelected());
            array[i] = ++index + "," + array[i] + array2[i];
            

        }
        return array2;
    }

    public String[] CharSplitBy11Count() {
        input  = jTextField1.getText();
        int count = 0;
        int RowNum = 0;
        int totalSubstrings = (int) Math.ceil((double) input.length() / substringSize);
        strSubstrings = new String[totalSubstrings];
        String password [] = new String[totalSubstrings];
        input = input.replaceAll("[^0-9]", "");
        int szam = 0;
        for (int i = 0; i < input.length(); i = i + substringSize) {
            strSubstrings[szam++] = input.substring(i, Math.min(i + substringSize, input.length()));
            strSubstrings[count] = strSubstrings[count].replaceAll("[^0-9]", "");
            strSubstrings[count] = strSubstrings[count].replaceFirst("06", "36");
            strSubstrings[count] = ++RowNum +","+ strSubstrings[count] + output;
            password[count] = rp.RandomPASS(Integer.parseInt(DBSZAM.getText()), NagyCHEK.isSelected(), kisCHEK.isSelected(), specCHEK.isSelected(), szamokCHEK.isSelected());
            strSubstrings[count] =  strSubstrings[count] + password[count];
            jList2.setListData(password);
            count++;
        }
        return strSubstrings;
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FELULET.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FELULET.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FELULET.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FELULET.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FELULET().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DBSZAM;
    private javax.swing.JCheckBox NagyCHEK;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JCheckBox kisCHEK;
    private javax.swing.JTextField passText;
    private javax.swing.JCheckBox specCHEK;
    private javax.swing.JCheckBox szamokCHEK;
    private javax.swing.JTextField telszamTEXT;
    // End of variables declaration//GEN-END:variables
}
